sudo: required

services:
  - docker

script:
- docker build -t asimov-deploy/asimov-deploy:build . -f Dockerfile.build
- docker run -it --rm --name test asimov-deploy/asimov-deploy:build

deploy:
  provider: npm
  email: asimov.deploy@gmail.com
  skip_cleanup: true
  api_key:
    secure: LKC9vElJGcZTTblwbFamkX2EATbpgjO4wghNAivzIYtn5Mho6h46Vlyw3u6UtobcCT9XS+nzklzFYdFSyT0NkhrCmZwrYw4nytjieyFyru/JRHkr8tIhNL0cbqsRYoqPXgpaRvDxX46iAHYAHB9wvt9UZ+HHPQCekq/aZGNrS5M=
  on:
    repo: asimov-deploy/asimov-deploy
    branch: master
